### ISSUE TITLE
Demo link is broken

### ISSUE THREAD

**Issue by peter279k** [hollodotme/fast-cgi-client-demo#1]
As title, the [demonstration link](http://demo.fast-cgi-client.de) is not available.

And it should be fixed.

**Comment by hollodotme** [comment]
There is no online demo anymore. You can run the demo via docker-compose on your machine. Please see [README.md](https://github.com/hollodotme/fast-cgi-client-demo/README.md) for instructions.

**Comment by peter279k** [comment]
The [README.md](https://github.com/hollodotme/fast-cgi-client-demo/README.md) is not found, and I think it should be `https://github.com/hollodotme/fast-cgi-client-demo/README.md`.

**Comment by hollodotme** [comment]
Sorry, the correct link is: https://github.com/hollodotme/fast-cgi-client-demo/blob/master/README.md
